apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  labels:
    name: kubia-manual
spec:
  containers:
  - name: kubia-manual
    image: josephassiga/kubia
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        protocol: TCP
